/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container": "#1b1f2b",
        "on-primary": "#00363a",
        "secondary": "#ecb2ff",
        "surface-container-low": "#171b27",
        "inverse-on-surface": "#2c303c",
        "on-primary-fixed-variant": "#004f54",
        "surface-dim": "#0f131e",
        "tertiary-container": "#e1d2ff",
        "surface": "#0f131e",
        "secondary-fixed-dim": "#ecb2ff",
        "surface-variant": "#313441",
        "primary-fixed": "#7df4ff",
        "surface-container-lowest": "#0a0e19",
        "on-primary-fixed": "#002022",
        "on-secondary-fixed": "#320047",
        "inverse-surface": "#dfe2f2",
        "tertiary": "#faf3ff",
        "error": "#ffb4ab",
        "on-error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#5700c9",
        "on-tertiary-fixed": "#23005b",
        "background": "#0f131e",
        "on-error": "#690005",
        "surface-container-highest": "#313441",
        "on-primary-container": "#006970",
        "primary-fixed-dim": "#00dbe9",
        "on-tertiary": "#3c0090",
        "tertiary-fixed": "#e9ddff",
        "secondary-container": "#cf5cff",
        "primary": "#dbfcff",
        "secondary-fixed": "#f8d8ff",
        "inverse-primary": "#006970",
        "error-container": "#93000a",
        "outline": "#849495",
        "on-surface": "#dfe2f2",
        "on-surface-variant": "#b9cacb",
        "primary-container": "#00f0ff",
        "on-tertiary-container": "#7213ff",
        "tertiary-fixed-dim": "#d1bcff",
        "on-secondary-container": "#480063",
        "surface-tint": "#00dbe9",
        "surface-bright": "#353945",
        "on-secondary-fixed-variant": "#74009f",
        "on-background": "#dfe2f2",
        "outline-variant": "#3b494b",
        "on-secondary": "#520071",
        "surface-container-high": "#262a36"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: { "DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px" },
    },
  },
  plugins: [],
}